In [1]:
#importing libraries
from sklearn import datasets
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [2]:
#reading training data set
mm = pd.read_csv('/Users/saptarshimondal/Documents/1.Course_Materials_MSDS/2nd SEM/CSCE 670 ISR/3.Project/MFlix-RecommenderSystem/src/data_big/Merged_Movies_data.csv')
print("First few rows of the training dataset:")
mm

First few rows of the training dataset:

,movieId,imdbId,tmdbId,title,original_language,tagline,overview,popularity,adult,poster_path,...,status,video,vote_average,vote_count,keywords,cast,crew,original_title,imdb_id,poster_working_url
0,1,114709,862.0,Toy Story,en,NaN,"Led by Woody, Andy's toys live happily in his ...",21.946943,False,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,...,Released,False,7.7,5415.0,"[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",Toy Story,tt0114709,Image not found
1,2,113497,8844.0,Jumanji,en,Roll the dice and unleash the excitement!,When siblings Judy and Peter discover an encha...,17.015539,False,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,...,Released,False,6.9,2413.0,"[{'id': 10090, 'name': 'board game'}, {'id': 1...","[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",Jumanji,tt0113497,https://image.tmdb.org/t/p/w500/vzmL6fP7aPKNKP...
2,3,113228,15602.0,Grumpier Old Men,en,Still Yelling. Still Fighting. Still Ready for...,A family wedding reignites the ancient feud be...,11.712900,False,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,...,Released,False,6.5,92.0,"[{'id': 1495, 'name': 'fishing'}, {'id': 12392...","[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",Grumpier Old Men,tt0113228,Image not found
3,4,114885,31357.0,Waiting to Exhale,en,Friends are the people who let you be yourself...,"Cheated on, mistreated and stepped on, the wom...",3.859495,False,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,...,Released,False,6.1,34.0,"[{'id': 818, 'name': 'based on novel'}, {'id':...","[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",Waiting to Exhale,tt0114885,Image not found
4,5,113041,11862.0,Father of the Bride Part II,en,Just When His World Is Back To Normal... He's ...,Just when George Banks has recovered from his ...,8.387519,False,/e64sOI48hQXyru7naBFyssKFxVd.jpg,...,Released,False,5.7,173.0,"[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...","[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",Father of the Bride Part II,tt0113041,Image not found
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47286,172915,1462059,355426.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Image not found
47287,173347,371472,247263.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Image not found
47288,173535,459945,406403.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Image not found
47289,173739,76954,445739.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Image not found
47290,176075,6958022,445713.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Image not found

In [3]:
mm.shape

(47291, 30)

In [4]:
mm.isnull().sum()

movieId                      0
imdbId                       0
tmdbId                     219
title                      384
original_language          391
tagline                  26382
overview                  1375
popularity                 384
adult                      380
poster_path                779
budget                     380
genres                     380
homepage                 39242
belongs_to_collection    42689
production_companies       384
production_countries       384
release_date               468
revenue                    384
runtime                    648
spoken_languages           384
status                     466
video                      384
vote_average               384
vote_count                 384
keywords                   381
cast                       381
crew                       381
original_title             380
imdb_id                    397
poster_working_url           0
dtype: int64

In [5]:
movies_data = mm.drop(columns = [ 'original_language',
       'popularity', 'adult', 'revenue', 
        'status', 'video', 'vote_average', 'vote_count', 'belongs_to_collection', 'homepage', 'tagline', 'imdb_id', 'poster_path', 'original_title'] , axis = 1 )

In [6]:
movies_data.columns

Index(['movieId', 'imdbId', 'tmdbId', 'title', 'overview', 'budget', 'genres',
       'production_companies', 'production_countries', 'release_date',
       'runtime', 'spoken_languages', 'keywords', 'cast', 'crew',
       'poster_working_url'],
      dtype='object')

In [7]:
movies_data.isnull().sum()

movieId                    0
imdbId                     0
tmdbId                   219
title                    384
overview                1375
budget                   380
genres                   380
production_companies     384
production_countries     384
release_date             468
runtime                  648
spoken_languages         384
keywords                 381
cast                     381
crew                     381
poster_working_url         0
dtype: int64

In [8]:
movies_data.dropna(inplace = True)

In [9]:
movies_data

,movieId,imdbId,tmdbId,title,overview,budget,genres,production_companies,production_countries,release_date,runtime,spoken_languages,keywords,cast,crew,poster_working_url
0,1,114709,862.0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",Image not found
1,2,113497,8844.0,Jumanji,When siblings Judy and Peter discover an encha...,65000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...","[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...","[{'id': 10090, 'name': 'board game'}, {'id': 1...","[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",https://image.tmdb.org/t/p/w500/vzmL6fP7aPKNKP...
2,3,113228,15602.0,Grumpier Old Men,A family wedding reignites the ancient feud be...,0.0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...","[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'id': 1495, 'name': 'fishing'}, {'id': 12392...","[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",Image not found
3,4,114885,31357.0,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",16000000.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'id': 818, 'name': 'based on novel'}, {'id':...","[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",Image not found
4,5,113041,11862.0,Father of the Bride Part II,Just when George Banks has recovered from his ...,0.0,"[{'id': 35, 'name': 'Comedy'}]","[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...","[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",Image not found
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46905,176267,102797,30840.0,Robin Hood,"Yet another version of the classic epic, with ...",0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...","[{'name': 'Westdeutscher Rundfunk (WDR)', 'id'...","[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",1991-05-13,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",[],"[{'cast_id': 1, 'character': 'Sir Robert Hode'...","[{'credit_id': '52fe44439251416c9100a899', 'de...",https://image.tmdb.org/t/p/w500/fQC46NglNiEMZB...
46907,176271,2028550,111109.0,Century of Birthing,An artist struggles to finish his work while a...,0.0,"[{'id': 18, 'name': 'Drama'}]","[{'name': 'Sine Olivia', 'id': 19653}]","[{'iso_3166_1': 'PH', 'name': 'Philippines'}]",2011-11-17,360.0,"[{'iso_639_1': 'tl', 'name': ''}]","[{'id': 2679, 'name': 'artist'}, {'id': 14531,...","[{'cast_id': 1002, 'character': 'Sister Angela...","[{'credit_id': '52fe4af1c3a36847f81e9b15', 'de...",https://image.tmdb.org/t/p/w500/xZkmxsNmYXJbKV...
46908,176273,303758,67758.0,Betrayal,"When one of her hits goes wrong, a professiona...",0.0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...","[{'name': 'American World Pictures', 'id': 6165}]","[{'iso_3166_1': 'US', 'name': 'United States o...",2003-08-01,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",[],"[{'cast_id': 6, 'character': 'Emily Shaw', 'cr...","[{'credit_id': '52fe4776c3a368484e0c8387', 'de...",Image not found
46909,176275,8536,227506.0,Satan Triumphant,"In a small town live two brothers, one a minis...",0.0,[],"[{'name': 'Yermoliev', 'id': 88753}]","[{'iso_3166_1': 'RU', 'name': 'Russia'}]",1917-10-21,87.0,[],[],"[{'cast_id': 2, 'character': '', 'credit_id': ...","[{'credit_id': '533bccebc3a36844cf0011a7', 'de...",Image not found
46910,176279,6980792,461257.0,Queerama,50 years after decriminalisation of homosexual...,0.0,[],[],"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",2017-06-09,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",[],[],"[{'credit_id': '593e676c92514105b702e68e', 'de...",https://image.tmdb.org/t/p/w500/s5UkZt6NTsrS7Z...

In [10]:
movies_data.shape

(45840, 16)

In [11]:
movies_data.isnull().sum()

movieId                 0
imdbId                  0
tmdbId                  0
title                   0
overview                0
budget                  0
genres                  0
production_companies    0
production_countries    0
release_date            0
runtime                 0
spoken_languages        0
keywords                0
cast                    0
crew                    0
poster_working_url      0
dtype: int64

In [12]:
movies_data_dup = movies_data.duplicated().sum()
movies_data_dup

1392

In [13]:
movies_data_new = movies_data.drop_duplicates()
movies_data_new

,movieId,imdbId,tmdbId,title,overview,budget,genres,production_companies,production_countries,release_date,runtime,spoken_languages,keywords,cast,crew,poster_working_url
0,1,114709,862.0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",Image not found
1,2,113497,8844.0,Jumanji,When siblings Judy and Peter discover an encha...,65000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...","[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...","[{'id': 10090, 'name': 'board game'}, {'id': 1...","[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",https://image.tmdb.org/t/p/w500/vzmL6fP7aPKNKP...
2,3,113228,15602.0,Grumpier Old Men,A family wedding reignites the ancient feud be...,0.0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...","[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'id': 1495, 'name': 'fishing'}, {'id': 12392...","[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",Image not found
3,4,114885,31357.0,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",16000000.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'id': 818, 'name': 'based on novel'}, {'id':...","[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",Image not found
4,5,113041,11862.0,Father of the Bride Part II,Just when George Banks has recovered from his ...,0.0,"[{'id': 35, 'name': 'Comedy'}]","[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...","[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",Image not found
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46905,176267,102797,30840.0,Robin Hood,"Yet another version of the classic epic, with ...",0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...","[{'name': 'Westdeutscher Rundfunk (WDR)', 'id'...","[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",1991-05-13,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",[],"[{'cast_id': 1, 'character': 'Sir Robert Hode'...","[{'credit_id': '52fe44439251416c9100a899', 'de...",https://image.tmdb.org/t/p/w500/fQC46NglNiEMZB...
46907,176271,2028550,111109.0,Century of Birthing,An artist struggles to finish his work while a...,0.0,"[{'id': 18, 'name': 'Drama'}]","[{'name': 'Sine Olivia', 'id': 19653}]","[{'iso_3166_1': 'PH', 'name': 'Philippines'}]",2011-11-17,360.0,"[{'iso_639_1': 'tl', 'name': ''}]","[{'id': 2679, 'name': 'artist'}, {'id': 14531,...","[{'cast_id': 1002, 'character': 'Sister Angela...","[{'credit_id': '52fe4af1c3a36847f81e9b15', 'de...",https://image.tmdb.org/t/p/w500/xZkmxsNmYXJbKV...
46908,176273,303758,67758.0,Betrayal,"When one of her hits goes wrong, a professiona...",0.0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...","[{'name': 'American World Pictures', 'id': 6165}]","[{'iso_3166_1': 'US', 'name': 'United States o...",2003-08-01,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",[],"[{'cast_id': 6, 'character': 'Emily Shaw', 'cr...","[{'credit_id': '52fe4776c3a368484e0c8387', 'de...",Image not found
46909,176275,8536,227506.0,Satan Triumphant,"In a small town live two brothers, one a minis...",0.0,[],"[{'name': 'Yermoliev', 'id': 88753}]","[{'iso_3166_1': 'RU', 'name': 'Russia'}]",1917-10-21,87.0,[],[],"[{'cast_id': 2, 'character': '', 'credit_id': ...","[{'credit_id': '533bccebc3a36844cf0011a7', 'de...",Image not found
46910,176279,6980792,461257.0,Queerama,50 years after decriminalisation of homosexual...,0.0,[],[],"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",2017-06-09,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",[],[],"[{'credit_id': '593e676c92514105b702e68e', 'de...",https://image.tmdb.org/t/p/w500/s5UkZt6NTsrS7Z...

In [14]:
movies_data_new.duplicated().sum()

0

In [15]:
movies_data_new.shape

(44448, 16)

In [17]:
import json
file_path = '/Users/saptarshimondal/Documents/1.Course_Materials_MSDS/2nd SEM/CSCE 670 ISR/3.Project/MFlix-RecommenderSystem/src/output/Working_poster_MovieID.json'

with open(file_path, 'r') as file:
    movie_id_lit = json.load(file)

In [19]:
type(movie_id_lit)

list

In [20]:
def check_working_url(row):
    if row['movieId'] not in movie_id_lit:
        return 'NF'
    else:
        return row['poster_working_url']
    
movies_data_new['final_poster_url'] = movies_data_new.apply(check_working_url, axis =1 )

In [23]:
sum(movies_data_new['final_poster_url'] != 'NF')

3200

In [25]:
movies_data_new.drop(columns = ['poster_working_url'], axis = 1, inplace = True)

In [26]:
movies_data_new

,movieId,imdbId,tmdbId,title,overview,budget,genres,production_companies,production_countries,release_date,runtime,spoken_languages,keywords,cast,crew,final_poster_url
0,1,114709,862.0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",NF
1,2,113497,8844.0,Jumanji,When siblings Judy and Peter discover an encha...,65000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...","[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...","[{'id': 10090, 'name': 'board game'}, {'id': 1...","[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",https://image.tmdb.org/t/p/w500/vzmL6fP7aPKNKP...
2,3,113228,15602.0,Grumpier Old Men,A family wedding reignites the ancient feud be...,0.0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...","[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'id': 1495, 'name': 'fishing'}, {'id': 12392...","[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",NF
3,4,114885,31357.0,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",16000000.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'id': 818, 'name': 'based on novel'}, {'id':...","[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",NF
4,5,113041,11862.0,Father of the Bride Part II,Just when George Banks has recovered from his ...,0.0,"[{'id': 35, 'name': 'Comedy'}]","[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...","[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",NF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46905,176267,102797,30840.0,Robin Hood,"Yet another version of the classic epic, with ...",0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...","[{'name': 'Westdeutscher Rundfunk (WDR)', 'id'...","[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",1991-05-13,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",[],"[{'cast_id': 1, 'character': 'Sir Robert Hode'...","[{'credit_id': '52fe44439251416c9100a899', 'de...",NF
46907,176271,2028550,111109.0,Century of Birthing,An artist struggles to finish his work while a...,0.0,"[{'id': 18, 'name': 'Drama'}]","[{'name': 'Sine Olivia', 'id': 19653}]","[{'iso_3166_1': 'PH', 'name': 'Philippines'}]",2011-11-17,360.0,"[{'iso_639_1': 'tl', 'name': ''}]","[{'id': 2679, 'name': 'artist'}, {'id': 14531,...","[{'cast_id': 1002, 'character': 'Sister Angela...","[{'credit_id': '52fe4af1c3a36847f81e9b15', 'de...",https://image.tmdb.org/t/p/w500/xZkmxsNmYXJbKV...
46908,176273,303758,67758.0,Betrayal,"When one of her hits goes wrong, a professiona...",0.0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...","[{'name': 'American World Pictures', 'id': 6165}]","[{'iso_3166_1': 'US', 'name': 'United States o...",2003-08-01,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",[],"[{'cast_id': 6, 'character': 'Emily Shaw', 'cr...","[{'credit_id': '52fe4776c3a368484e0c8387', 'de...",NF
46909,176275,8536,227506.0,Satan Triumphant,"In a small town live two brothers, one a minis...",0.0,[],"[{'name': 'Yermoliev', 'id': 88753}]","[{'iso_3166_1': 'RU', 'name': 'Russia'}]",1917-10-21,87.0,[],[],"[{'cast_id': 2, 'character': '', 'credit_id': ...","[{'credit_id': '533bccebc3a36844cf0011a7', 'de...",NF
46910,176279,6980792,461257.0,Queerama,50 years after decriminalisation of homosexual...,0.0,[],[],"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",2017-06-09,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",[],[],"[{'credit_id': '593e676c92514105b702e68e', 'de...",NF

In [27]:
movies_data_new.to_csv('/Users/saptarshimondal/Documents/1.Course_Materials_MSDS/2nd SEM/CSCE 670 ISR/3.Project/MFlix-RecommenderSystem/src/output/Movies_dataset.csv')

#### Final movies_data with no missing values shape(6139*26)

In [54]:
movies_data['popularity'].value_counts()

3.008299    8
0.000844    8
3.185256    8
0.000220    6
0.000308    6
           ..
0.619084    1
9.482806    1
0.661981    1
0.584232    1
0.163015    1
Name: popularity, Length: 5951, dtype: int64

In [55]:
movies_data['adult'].value_counts()

False    6135
True        4
Name: adult, dtype: int64

In [22]:
movies_data.loc[0,'crew']

'[{\'credit_id\': \'52fe4284c3a36847f8024f49\', \'department\': \'Directing\', \'gender\': 2, \'id\': 7879, \'job\': \'Director\', \'name\': \'John Lasseter\', \'profile_path\': \'/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f4f\', \'department\': \'Writing\', \'gender\': 2, \'id\': 12891, \'job\': \'Screenplay\', \'name\': \'Joss Whedon\', \'profile_path\': \'/dTiVsuaTVTeGmvkhcyJvKp2A5kr.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f55\', \'department\': \'Writing\', \'gender\': 2, \'id\': 7, \'job\': \'Screenplay\', \'name\': \'Andrew Stanton\', \'profile_path\': \'/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f5b\', \'department\': \'Writing\', \'gender\': 2, \'id\': 12892, \'job\': \'Screenplay\', \'name\': \'Joel Cohen\', \'profile_path\': \'/dAubAiZcvKFbboWlj7oXOkZnTSu.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f61\', \'department\': \'Writing\', \'gender\': 0, \'id\': 12893, \'job\': \'Screenplay\', \'name\': \'Alec Sokolow\', \'profile_path\': \'/v79vlRYi94BZUQnkkyznbGUZLjT.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f67\', \'department\': \'Production\', \'gender\': 1, \'id\': 12894, \'job\': \'Producer\', \'name\': \'Bonnie Arnold\', \'profile_path\': None}, {\'credit_id\': \'52fe4284c3a36847f8024f6d\', \'department\': \'Production\', \'gender\': 0, \'id\': 12895, \'job\': \'Executive Producer\', \'name\': \'Ed Catmull\', \'profile_path\': None}, {\'credit_id\': \'52fe4284c3a36847f8024f73\', \'department\': \'Production\', \'gender\': 2, \'id\': 12896, \'job\': \'Producer\', \'name\': \'Ralph Guggenheim\', \'profile_path\': None}, {\'credit_id\': \'52fe4284c3a36847f8024f79\', \'department\': \'Production\', \'gender\': 2, \'id\': 12897, \'job\': \'Executive Producer\', \'name\': \'Steve Jobs\', \'profile_path\': \'/mOMP3SwD5qWQSR0ldCIByd3guTV.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f8b\', \'department\': \'Editing\', \'gender\': 2, \'id\': 8, \'job\': \'Editor\', \'name\': \'Lee Unkrich\', \'profile_path\': \'/bdTCCXjgOV3YyaNmLGYGOxFQMOc.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f91\', \'department\': \'Art\', \'gender\': 2, \'id\': 7883, \'job\': \'Art Direction\', \'name\': \'Ralph Eggleston\', \'profile_path\': \'/uUfcGKDsKO1aROMpXRs67Hn6RvR.jpg\'}, {\'credit_id\': \'598331bf925141421201044b\', \'department\': \'Editing\', \'gender\': 2, \'id\': 1168870, \'job\': \'Editor\', \'name\': \'Robert Gordon\', \'profile_path\': None}, {\'credit_id\': \'5892168cc3a36809660095f9\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1552883, \'job\': \'Foley Editor\', \'name\': \'Mary Helen Leasman\', \'profile_path\': None}, {\'credit_id\': \'5531824d9251415289000945\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1453514, \'job\': \'Animation\', \'name\': \'Kim Blanchette\', \'profile_path\': None}, {\'credit_id\': \'589215969251412dcb009bf6\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1414182, \'job\': \'ADR Editor\', \'name\': \'Marilyn McCoppen\', \'profile_path\': None}, {\'credit_id\': \'589217099251412dc500a018\', \'department\': \'Sound\', \'gender\': 2, \'id\': 7885, \'job\': \'Orchestrator\', \'name\': \'Randy Newman\', \'profile_path\': \'/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg\'}, {\'credit_id\': \'5693e6b29251417b0e0000e3\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1429549, \'job\': \'Color Timer\', \'name\': \'Dale E. Grahn\', \'profile_path\': None}, {\'credit_id\': \'572e2522c3a36869e6001a9c\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 7949, \'job\': \'CG Painter\', \'name\': \'Robin Cooper\', \'profile_path\': None}, {\'credit_id\': \'574f12309251415ca1000012\', \'department\': \'Writing\', \'gender\': 2, \'id\': 7879, \'job\': \'Original Story\', \'name\': \'John Lasseter\', \'profile_path\': \'/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg\'}, {\'credit_id\': \'574f1240c3a3682e7300001c\', \'department\': \'Writing\', \'gender\': 2, \'id\': 12890, \'job\': \'Original Story\', \'name\': \'Pete Docter\', \'profile_path\': \'/r6ngPgnReA3RHmKjmSoVsc6Awjp.jpg\'}, {\'credit_id\': \'574f12519251415c92000015\', \'department\': \'Writing\', \'gender\': 0, \'id\': 7911, \'job\': \'Original Story\', \'name\': \'Joe Ranft\', \'profile_path\': \'/f1BoWC2JbCcfP1e5hKfGsxkHzVU.jpg\'}, {\'credit_id\': \'574f12cec3a3682e82000022\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1629419, \'job\': \'Post Production Supervisor\', \'name\': \'Patsy Bouge\', \'profile_path\': None}, {\'credit_id\': \'574f14f19251415ca1000082\', \'department\': \'Art\', \'gender\': 0, \'id\': 7961, \'job\': \'Sculptor\', \'name\': \'Norm DeCarlo\', \'profile_path\': None}, {\'credit_id\': \'5751ae4bc3a3683772002b7f\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 12905, \'job\': \'Animation Director\', \'name\': \'Ash Brannon\', \'profile_path\': \'/6ueWgPEEBHvS3De2BHYQnYjRTig.jpg\'}, {\'credit_id\': \'5891edbe9251412dc5007cd6\', \'department\': \'Sound\', \'gender\': 2, \'id\': 7885, \'job\': \'Music\', \'name\': \'Randy Newman\', \'profile_path\': \'/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg\'}, {\'credit_id\': \'589213d39251412dc8009832\', \'department\': \'Directing\', \'gender\': 0, \'id\': 1748707, \'job\': \'Layout\', \'name\': \'Roman Figun\', \'profile_path\': None}, {\'credit_id\': \'5892173dc3a3680968009351\', \'department\': \'Sound\', \'gender\': 2, \'id\': 4949, \'job\': \'Orchestrator\', \'name\': \'Don Davis\', \'profile_path\': None}, {\'credit_id\': \'589217cec3a3686b0a0052ba\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1372885, \'job\': \'Music Editor\', \'name\': \'James Flamberg\', \'profile_path\': None}, {\'credit_id\': \'58921831c3a3686348004a64\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1739962, \'job\': \'Negative Cutter\', \'name\': \'Mary Beth Smith\', \'profile_path\': None}, {\'credit_id\': \'58921838c3a36809700096c0\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748513, \'job\': \'Negative Cutter\', \'name\': \'Rick Mackay\', \'profile_path\': None}, {\'credit_id\': \'589218429251412dd1009d1b\', \'department\': \'Art\', \'gender\': 0, \'id\': 1458006, \'job\': \'Title Designer\', \'name\': \'Susan Bradley\', \'profile_path\': None}, {\'credit_id\': \'5891ed99c3a3680966007670\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1748557, \'job\': \'Supervising Technical Director\', \'name\': \'William Reeves\', \'profile_path\': None}, {\'credit_id\': \'5891edcec3a3686b0a002eb2\', \'department\': \'Sound\', \'gender\': 2, \'id\': 7885, \'job\': \'Songs\', \'name\': \'Randy Newman\', \'profile_path\': \'/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg\'}, {\'credit_id\': \'5891edf9c3a36809700075e6\', \'department\': \'Writing\', \'gender\': 2, \'id\': 7, \'job\': \'Original Story\', \'name\': \'Andrew Stanton\', \'profile_path\': \'/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg\'}, {\'credit_id\': \'58920f0b9251412dd7009104\', \'department\': \'Crew\', \'gender\': 2, \'id\': 12890, \'job\': \'Supervising Animator\', \'name\': \'Pete Docter\', \'profile_path\': \'/r6ngPgnReA3RHmKjmSoVsc6Awjp.jpg\'}, {\'credit_id\': \'58920f1fc3a3680977009021\', \'department\': \'Sound\', \'gender\': 2, \'id\': 2216, \'job\': \'Sound Designer\', \'name\': \'Gary Rydstrom\', \'profile_path\': \'/jZpr1nVfO7lldWI0YtmP1FGw7Rj.jpg\'}, {\'credit_id\': \'58920f389251412dd700912d\', \'department\': \'Production\', \'gender\': 0, \'id\': 12909, \'job\': \'Production Supervisor\', \'name\': \'Karen Robert Jackson\', \'profile_path\': None}, {\'credit_id\': \'58920fbd9251412dcb00969c\', \'department\': \'Crew\', \'gender\': 0, \'id\': 953331, \'job\': \'Executive Music Producer\', \'name\': \'Chris Montan\', \'profile_path\': None}, {\'credit_id\': \'589210069251412dd7009219\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 7893, \'job\': \'Animation Director\', \'name\': \'Rich Quade\', \'profile_path\': None}, {\'credit_id\': \'589210329251412dcd00943b\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8025, \'job\': \'Animation\', \'name\': \'Michael Berenstein\', \'profile_path\': None}, {\'credit_id\': \'5892103bc3a368096a009180\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 78009, \'job\': \'Animation\', \'name\': \'Colin Brady\', \'profile_path\': None}, {\'credit_id\': \'5892105dc3a3680968008db2\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748682, \'job\': \'Animation\', \'name\': \'Davey Crockett Feiten\', \'profile_path\': None}, {\'credit_id\': \'589210669251412dcd009466\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1454030, \'job\': \'Animation\', \'name\': \'Angie Glocka\', \'profile_path\': None}, {\'credit_id\': \'5892107c9251412dd1009613\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748683, \'job\': \'Animation\', \'name\': \'Rex Grignon\', \'profile_path\': None}, {\'credit_id\': \'5892108ac3a3680973008d3f\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748684, \'job\': \'Animation\', \'name\': \'Tom K. Gurney\', \'profile_path\': None}, {\'credit_id\': \'58921093c3a3686348004477\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 8029, \'job\': \'Animation\', \'name\': \'Jimmy Hayward\', \'profile_path\': \'/lTDRpudEY7BDwTefXbXzMlmb0ui.jpg\'}, {\'credit_id\': \'5892109b9251412dcd0094b0\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1426773, \'job\': \'Animation\', \'name\': \'Hal T. Hickel\', \'profile_path\': None}, {\'credit_id\': \'589210a29251412dc5009a29\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8035, \'job\': \'Animation\', \'name\': \'Karen Kiser\', \'profile_path\': None}, {\'credit_id\': \'589210ccc3a3680977009191\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748688, \'job\': \'Animation\', \'name\': \'Anthony B. LaMolinara\', \'profile_path\': None}, {\'credit_id\': \'589210d7c3a3686b0a004c1f\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 587314, \'job\': \'Animation\', \'name\': \'Guionne Leroy\', \'profile_path\': None}, {\'credit_id\': \'589210e1c3a36809770091a7\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7918, \'job\': \'Animation\', \'name\': \'Bud Luckey\', \'profile_path\': \'/pcCh7G19FKMNijmPQg1PMH1btic.jpg\'}, {\'credit_id\': \'589210ee9251412dc200978a\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748689, \'job\': \'Animation\', \'name\': \'Les Major\', \'profile_path\': None}, {\'credit_id\': \'589210fa9251412dc8009595\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7892, \'job\': \'Animation\', \'name\': \'Glenn McQueen\', \'profile_path\': None}, {\'credit_id\': \'589211029251412dc8009598\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 555795, \'job\': \'Animation\', \'name\': \'Mark Oftedal\', \'profile_path\': None}, {\'credit_id\': \'5892110b9251412dc800959d\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7882, \'job\': \'Animation\', \'name\': \'Jeff Pidgeon\', \'profile_path\': \'/yLddkg5HcgbJg00cS13GVBnP0HY.jpg\'}, {\'credit_id\': \'58921113c3a36863480044e4\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8017, \'job\': \'Animation\', \'name\': \'Jeff Pratt\', \'profile_path\': None}, {\'credit_id\': \'5892111c9251412dcb0097e9\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1184140, \'job\': \'Animation\', \'name\': \'Steve Rabatich\', \'profile_path\': None}, {\'credit_id\': \'58921123c3a36809700090f6\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8049, \'job\': \'Animation\', \'name\': \'Roger Rose\', \'profile_path\': None}, {\'credit_id\': \'5892112b9251412dcb0097fb\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1509559, \'job\': \'Animation\', \'name\': \'Steve Segal\', \'profile_path\': None}, {\'credit_id\': \'589211349251412dc80095c3\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748691, \'job\': \'Animation\', \'name\': \'Doug Sheppeck\', \'profile_path\': None}, {\'credit_id\': \'5892113cc3a3680970009106\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8050, \'job\': \'Animation\', \'name\': \'Alan Sperling\', \'profile_path\': None}, {\'credit_id\': \'58921148c3a3686b0a004c99\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8010, \'job\': \'Animation\', \'name\': \'Doug Sweetland\', \'profile_path\': None}, {\'credit_id\': \'58921150c3a3680966009125\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8044, \'job\': \'Animation\', \'name\': \'David Tart\', \'profile_path\': None}, {\'credit_id\': \'589211629251412dc5009b00\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1454034, \'job\': \'Animation\', \'name\': \'Ken Willard\', \'profile_path\': None}, {\'credit_id\': \'589211c1c3a3686b0a004d28\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 7887, \'job\': \'Visual Effects Supervisor\', \'name\': \'Thomas Porter\', \'profile_path\': None}, {\'credit_id\': \'589211d4c3a3680968008ed9\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1406878, \'job\': \'Visual Effects\', \'name\': \'Mark Thomas Henne\', \'profile_path\': None}, {\'credit_id\': \'589211f59251412dd4008e65\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748698, \'job\': \'Visual Effects\', \'name\': \'Oren Jacob\', \'profile_path\': None}, {\'credit_id\': \'58921242c3a368096a00939b\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748699, \'job\': \'Visual Effects\', \'name\': \'Darwyn Peachey\', \'profile_path\': None}, {\'credit_id\': \'5892124b9251412dc5009bd2\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748701, \'job\': \'Visual Effects\', \'name\': \'Mitch Prater\', \'profile_path\': None}, {\'credit_id\': \'58921264c3a3686b0a004dbf\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748703, \'job\': \'Visual Effects\', \'name\': \'Brian M. Rosen\', \'profile_path\': None}, {\'credit_id\': \'589212709251412dcd009676\', \'department\': \'Lighting\', \'gender\': 1, \'id\': 12912, \'job\': \'Lighting Supervisor\', \'name\': \'Sharon Calahan\', \'profile_path\': None}, {\'credit_id\': \'5892127fc3a3686b0a004de5\', \'department\': \'Lighting\', \'gender\': 0, \'id\': 7899, \'job\': \'Lighting Supervisor\', \'name\': \'Galyn Susman\', \'profile_path\': None}, {\'credit_id\': \'589212cdc3a3680970009268\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 12915, \'job\': \'CG Painter\', \'name\': \'William Cone\', \'profile_path\': None}, {\'credit_id\': \'5892130f9251412dc8009791\', \'department\': \'Art\', \'gender\': 0, \'id\': 1748705, \'job\': \'Sculptor\', \'name\': \'Shelley Daniels Lekven\', \'profile_path\': None}, {\'credit_id\': \'5892131c9251412dd4008f4c\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7889, \'job\': \'Character Designer\', \'name\': \'Bob Pauley\', \'profile_path\': None}, {\'credit_id\': \'589213249251412dd100987b\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7918, \'job\': \'Character Designer\', \'name\': \'Bud Luckey\', \'profile_path\': \'/pcCh7G19FKMNijmPQg1PMH1btic.jpg\'}, {\'credit_id\': \'5892132b9251412dc80097b1\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7, \'job\': \'Character Designer\', \'name\': \'Andrew Stanton\', \'profile_path\': \'/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg\'}, {\'credit_id\': \'58921332c3a368634800467b\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 12915, \'job\': \'Character Designer\', \'name\': \'William Cone\', \'profile_path\': None}, {\'credit_id\': \'5892135f9251412dd4008f90\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748706, \'job\': \'Character Designer\', \'name\': \'Steve Johnson\', \'profile_path\': None}, {\'credit_id\': \'58921384c3a3680973008fd4\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1176752, \'job\': \'Character Designer\', \'name\': \'Dan Haskett\', \'profile_path\': None}, {\'credit_id\': \'5892138e9251412dc20099fc\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1088034, \'job\': \'Character Designer\', \'name\': \'Tom Holloway\', \'profile_path\': \'/a0r0T2usTBpgMI5aZbRBDW1fTl8.jpg\'}, {\'credit_id\': \'58921395c3a368097700942f\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1447465, \'job\': \'Character Designer\', \'name\': \'Jean Gillmore\', \'profile_path\': None}, {\'credit_id\': \'589213e2c3a3680973009026\', \'department\': \'Directing\', \'gender\': 0, \'id\': 1748709, \'job\': \'Layout\', \'name\': \'Desirée Mourad\', \'profile_path\': None}, {\'credit_id\': \'589214099251412dc5009d57\', \'department\': \'Art\', \'gender\': 0, \'id\': 1748710, \'job\': \'Set Dresser\', \'name\': "Kelly O\'Connell", \'profile_path\': None}, {\'credit_id\': \'58921411c3a3686b0a004f70\', \'department\': \'Art\', \'gender\': 0, \'id\': 1443471, \'job\': \'Set Dresser\', \'name\': \'Sonoko Konishi\', \'profile_path\': None}, {\'credit_id\': \'58921434c3a368096a00956e\', \'department\': \'Art\', \'gender\': 0, \'id\': 1748711, \'job\': \'Set Dresser\', \'name\': \'Ann M. Rockwell\', \'profile_path\': None}, {\'credit_id\': \'5892144ac3a36809680090de\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748712, \'job\': \'Editorial Manager\', \'name\': \'Julie M. McDonald\', \'profile_path\': None}, {\'credit_id\': \'58921479c3a368096800910f\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1589729, \'job\': \'Assistant Editor\', \'name\': \'Robin Lee\', \'profile_path\': None}, {\'credit_id\': \'5892148b9251412dd10099cc\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748716, \'job\': \'Assistant Editor\', \'name\': \'Tom Freeman\', \'profile_path\': None}, {\'credit_id\': \'589214959251412dcb009b1f\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748717, \'job\': \'Assistant Editor\', \'name\': \'Ada Cochavi\', \'profile_path\': None}, {\'credit_id\': \'5892149ec3a3686348004798\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1336438, \'job\': \'Assistant Editor\', \'name\': \'Dana Mulligan\', \'profile_path\': None}, {\'credit_id\': \'589214adc3a368096a0095db\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748718, \'job\': \'Editorial Coordinator\', \'name\': \'Deirdre Morrison\', \'profile_path\': None}, {\'credit_id\': \'589214c7c3a368097700952b\', \'department\': \'Production\', \'gender\': 0, \'id\': 1748719, \'job\': \'Production Coordinator\', \'name\': \'Lori Lombardo\', \'profile_path\': None}, {\'credit_id\': \'589214cec3a368096a009603\', \'department\': \'Production\', \'gender\': 0, \'id\': 1748720, \'job\': \'Production Coordinator\', \'name\': \'Ellen Devine\', \'profile_path\': None}, {\'credit_id\': \'589214e39251412dc8009904\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1468014, \'job\': \'Unit Publicist\', \'name\': \'Lauren Beth Strogoff\', \'profile_path\': None}, {\'credit_id\': \'58921544c3a3686b0a00507d\', \'department\': \'Sound\', \'gender\': 2, \'id\': 2216, \'job\': \'Sound Re-Recording Mixer\', \'name\': \'Gary Rydstrom\', \'profile_path\': \'/jZpr1nVfO7lldWI0YtmP1FGw7Rj.jpg\'}, {\'credit_id\': \'5892154c9251412dd1009a56\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1425978, \'job\': \'Sound Re-Recording Mixer\', \'name\': \'Gary Summers\', \'profile_path\': None}, {\'credit_id\': \'58921555c3a36809680091bd\', \'department\': \'Sound\', \'gender\': 2, \'id\': 8276, \'job\': \'Supervising Sound Editor\', \'name\': \'Tim Holland\', \'profile_path\': None}, {\'credit_id\': \'589215c39251412dcb009c12\', \'department\': \'Sound\', \'gender\': 0, \'id\': 7069, \'job\': \'Sound Effects Editor\', \'name\': \'Pat Jackson\', \'profile_path\': None}, {\'credit_id\': \'58921698c3a368096a009788\', \'department\': \'Crew\', \'gender\': 2, \'id\': 15894, \'job\': \'Sound Design Assistant\', \'name\': \'Tom Myers\', \'profile_path\': None}, {\'credit_id\': \'589216a89251412dc2009ca4\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1414177, \'job\': \'Assistant Sound Editor\', \'name\': \'J.R. 

In [56]:
movies_data['budget'].value_counts()

0.0            4876
20000000.0       34
5000000.0        33
4000000.0        32
10000000.0       32
               ...
2160000.0         1
5800000.0         1
60795000.0        1
258000000.0       1
3417000.0         1
Name: budget, Length: 370, dtype: int64

In [57]:
movies_data['genres'].value_counts()

[{'id': 18, 'name': 'Drama'}]                                                                                                 692
[{'id': 35, 'name': 'Comedy'}]                                                                                                463
[{'id': 99, 'name': 'Documentary'}]                                                                                           302
[]                                                                                                                            231
[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]                                                               176
                                                                                                                             ...
[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}, {'id': 36, 'name': 'History'}]                                  1
[{'id': 10769, 'name': 'Foreign'}, {'id': 35, 'name': 'Comedy'}]                                                                1
[{'id': 27, 'name': 'Horror'}, {'id': 53, 'name': 'Thriller'}, {'id': 10769, 'name': 'Foreign'}]                                1
[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 18, 'name': 'Drama'}, {'id': 10752, 'name': 'War'}]      1
[{'id': 35, 'name': 'Comedy'}, {'id': 14, 'name': 'Fantasy'}, {'id': 878, 'name': 'Science Fiction'}]                           1
Name: genres, Length: 1268, dtype: int64

In [58]:
movies_data['production_companies'].value_counts()

[]                                                                                                                                                                                                                                                                                  1372
[{'name': 'Metro-Goldwyn-Mayer (MGM)', 'id': 8411}]                                                                                                                                                                                                                                  120
[{'name': 'Twentieth Century Fox Film Corporation', 'id': 306}]                                                                                                                                                                                                                       78
[{'name': 'Warner Bros.', 'id': 6194}]                                                                                                                                                                                                                                                68
[{'name': 'Paramount Pictures', 'id': 4}]                                                                                                                                                                                                                                             55
                                                                                                                                                                                                                                                                                    ...
[{'name': 'Paramount Pictures', 'id': 4}, {'name': 'Appian Way', 'id': 562}, {'name': 'Phoenix Pictures', 'id': 11317}, {'name': 'Sikelia Productions', 'id': 23243}]                                                                                                                  1
[{'name': '20th Century Pictures', 'id': 4985}]                                                                                                                                                                                                                                        1
[{'name': 'Apipoulaï', 'id': 1076}, {'name': 'M6 Films', 'id': 1115}, {'name': 'Canal+', 'id': 5358}, {'name': 'TPS Star', 'id': 6586}, {'name': 'Grive Productions', 'id': 6877}, {'name': 'EuropaCorp', 'id': 6896}, {'name': 'M6', 'id': 11261}, {'name': 'W9', 'id': 34774}]       1
[{'name': 'Metro-Goldwyn-Mayer (MGM)', 'id': 8411}, {'name': 'Russflix', 'id': 13959}]                                                                                                                                                                                                 1
[{'name': 'Sine Olivia', 'id': 19653}]                                                                                                                                                                                                                                                 1
Name: production_companies, Length: 3583, dtype: int64

In [59]:
movies_data['production_countries'].value_counts()

[{'iso_3166_1': 'US', 'name': 'United States of America'}]                                                                                                                                     2349
[]                                                                                                                                                                                              633
[{'iso_3166_1': 'JP', 'name': 'Japan'}]                                                                                                                                                         277
[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]                                                                                                                                                276
[{'iso_3166_1': 'FR', 'name': 'France'}]                                                                                                                                                        251
                                                                                                                                                                                               ...
[{'iso_3166_1': 'DE', 'name': 'Germany'}, {'iso_3166_1': 'IT', 'name': 'Italy'}, {'iso_3166_1': 'NL', 'name': 'Netherlands'}, {'iso_3166_1': 'RU', 'name': 'Russia'}]                             1
[{'iso_3166_1': 'LU', 'name': 'Luxembourg'}]                                                                                                                                                      1
[{'iso_3166_1': 'DK', 'name': 'Denmark'}, {'iso_3166_1': 'FR', 'name': 'France'}, {'iso_3166_1': 'IS', 'name': 'Iceland'}, {'iso_3166_1': 'US', 'name': 'United States of America'}]              1
[{'iso_3166_1': 'IL', 'name': 'Israel'}, {'iso_3166_1': 'FR', 'name': 'France'}, {'iso_3166_1': 'DE', 'name': 'Germany'}, {'iso_3166_1': 'LB', 'name': 'Lebanon'}]                                1
[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso_3166_1': 'DE', 'name': 'Germany'}, {'iso_3166_1': 'GB', 'name': 'United Kingdom'}, {'iso_3166_1': 'US', 'name': 'United States of America'}]       1
Name: production_countries, Length: 545, dtype: int64

In [60]:
movies_data['release_date'].value_counts()

2005-09-03    17
2008-01-01    14
1981-01-01    13
2004-01-01    13
1989-01-01    13
              ..
2008-03-29     1
1960-12-01     1
1935-12-25     1
2003-04-10     1
2011-11-17     1
Name: release_date, Length: 4564, dtype: int64

In [61]:
movies_data['revenue'].value_counts()

0.0            5081
2500000.0         4
11000000.0        3
32000000.0        3
6000000.0         3
               ...
940335536.0       1
51142659.0        1
259175788.0       1
6746000.0         1
184770205.0       1
Name: revenue, Length: 1021, dtype: int64

In [62]:
movies_data['runtime'].value_counts()

90.0     316
95.0     201
100.0    200
93.0     159
92.0     139
        ...
252.0      1
925.0      1
237.0      1
207.0      1
34.0       1
Name: runtime, Length: 239, dtype: int64

In [63]:
movies_data['spoken_languages'].value_counts()

[{'iso_639_1': 'en', 'name': 'English'}]                                                                                                                                                                2902
[]                                                                                                                                                                                                       312
[{'iso_639_1': 'fr', 'name': 'Français'}]                                                                                                                                                                280
[{'iso_639_1': 'ja', 'name': '日本語'}]                                                                                                                                                                     258
[{'iso_639_1': 'ru', 'name': 'Pусский'}]                                                                                                                                                                 165
                                                                                                                                                                                                        ...
[{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'my', 'name': ''}, {'iso_639_1': 'th', 'name': 'ภาษาไทย'}]                                                                                          1
[{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'he', 'name': 'עִבְרִית'}]                                                                                  1
[{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'pt', 'name': 'Português'}, {'iso_639_1': 'ps', 'name': 'پښتو'}, {'iso_639_1': 'ru', 'name': 'Pусский'}, {'iso_639_1': 'ur', 'name': 'اردو'}]       1
[{'iso_639_1': 'ce', 'name': ''}, {'iso_639_1': 'cs', 'name': 'Český'}, {'iso_639_1': 'ru', 'name': 'Pусский'}]                                                                                            1
[{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'pl', 'name': 'Polski'}, {'iso_639_1': 'pt', 'name': 'Português'}]                                                                                  1
Name: spoken_languages, Length: 508, dtype: int64

In [21]:
movies_data['original_language'].value_counts()

en    32883
fr     2369
ja     1440
it     1292
de      997
      ...
jv        1
qu        1
la        1
fy        1
si        1
Name: original_language, Length: 89, dtype: int64

In [64]:
movies_data['status'].value_counts()

Released           6064
Rumored              37
Post Production      29
In Production         5
Planned               4
Name: status, dtype: int64

In [65]:
movies_data['video'].value_counts()

False    6130
True        9
Name: video, dtype: int64

In [66]:
movies_data['vote_average'].value_counts()

6.0    318
7.0    272
0.0    258
6.5    249
5.0    230
      ...
9.8      1
9.1      1
8.9      1
1.8      1
9.4      1
Name: vote_average, Length: 84, dtype: int64

In [67]:
movies_data['vote_count'].value_counts()

3.0       392
2.0       368
4.0       342
1.0       337
5.0       287
         ...
8226.0      1
1946.0      1
1007.0      1
1410.0      1
324.0       1
Name: vote_count, Length: 740, dtype: int64

In [68]:
movies_data = movies_data.drop(columns = ['adult', 'video', 'status'] , axis = 1 )

In [69]:
movies_data

,movieId,imdbId,tmdbId,title,original_language,overview,popularity,budget,genres,production_companies,...,release_date,revenue,runtime,spoken_languages,vote_average,vote_count,keywords,cast,crew,poster_working_url
1,2,113497,8844.0,Jumanji,en,When siblings Judy and Peter discover an encha...,17.015539,65000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...","[{'name': 'TriStar Pictures', 'id': 559}, {'na...",...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",6.9,2413.0,"[{'id': 10090, 'name': 'board game'}, {'id': 1...","[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",https://image.tmdb.org/t/p/w500/vzmL6fP7aPKNKP...
18,19,112281,9273.0,Ace Ventura: When Nature Calls,en,"Summoned from an ashram in Tibet, Ace finds hi...",8.205448,30000000.0,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...","[{'name': 'O Entertainment', 'id': 5682}, {'na...",...,1995-11-10,212385533.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",6.1,1128.0,"[{'id': 409, 'name': 'africa'}, {'id': 1551, '...","[{'cast_id': 1, 'character': 'Ace Ventura', 'c...","[{'credit_id': '52fe44dfc3a36847f80af28b', 'de...",https://image.tmdb.org/t/p/w500/wRlGnJhEzcxBjv...
19,20,113845,11517.0,Money Train,en,A vengeful New York transit cop decides to ste...,7.337906,60000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...","[{'name': 'Columbia Pictures', 'id': 5}]",...,1995-11-21,35431113.0,103.0,"[{'iso_639_1': 'en', 'name': 'English'}]",5.4,224.0,"[{'id': 380, 'name': 'brother brother relation...","[{'cast_id': 1, 'character': 'John', 'credit_i...","[{'credit_id': '52fe44509251416c750305a1', 'de...",https://image.tmdb.org/t/p/w500/jSozzzVOR2kfXg...
31,32,114746,63.0,Twelve Monkeys,en,"In the year 2035, convict James Cole reluctant...",12.297305,29500000.0,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...","[{'name': 'Universal Pictures', 'id': 33}, {'n...",...,1995-12-29,168840000.0,129.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",7.4,2470.0,"[{'id': 222, 'name': 'schizophrenia'}, {'id': ...","[{'cast_id': 41, 'character': 'James Cole', 'c...","[{'credit_id': '52fe4212c3a36847f8001ac7', 'de...",https://image.tmdb.org/t/p/w500/6Sj9wDu3YugthX...
33,34,112431,9598.0,Babe,en,Babe is a little pig who doesn't quite know hi...,14.404764,30000000.0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...","[{'name': 'Universal Pictures', 'id': 33}, {'n...",...,1995-07-18,254134910.0,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",6.0,756.0,"[{'id': 3020, 'name': 'sheep'}, {'id': 4931, '...","[{'cast_id': 1, 'character': 'Babe the Gallant...","[{'credit_id': '52fe450fc3a36847f80b9ff7', 'de...",https://image.tmdb.org/t/p/w500/gN6X3fwPya8pLf...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46894,176235,457437,14885.0,Pooh's Heffalump Halloween Movie,en,"It's Halloween in the 100 Acre Wood, and Roo's...",2.568495,0.0,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...","[{'name': 'Walt Disney Pictures', 'id': 2}]",...,2005-09-13,0.0,67.0,"[{'iso_639_1': 'en', 'name': 'English'}]",5.4,7.0,"[{'id': 3335, 'name': 'halloween'}, {'id': 193...","[{'cast_id': 1, 'character': 'Roo (voice)', 'c...","[{'credit_id': '52fe46249251416c7506e969', 'de...",https://image.tmdb.org/t/p/w500/yU6byKhpzHG1RF...
46898,176249,5690142,404604.0,Mom,hi,The bliss of a biology teacher’s family life i...,1.559596,0.0,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...","[{'name': 'Mad Films', 'id': 82459}, {'name': ...",...,2017-07-07,0.0,146.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",6.6,14.0,"[{'id': 155794, 'name': 'physical abuse'}, {'i...","[{'cast_id': 1, 'character': 'Devki Sabarwal',...","[{'credit_id': '58ee55bbc3a3683df500bd0f', 'de...",https://image.tmdb.org/t/p/w500/zZwbntqdfKdVgz...
46905,176267,102797,30840.0,Robin Hood,en,"Yet another version of the classic epic, with ...",5.683753,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...","[{'name': 'Westdeutscher Rundfunk (WDR)', 'id'...",...,1991-05-13,0.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",5.7,26.0,[],"[{'cast_id': 1, 'character': 'Sir Robert Hode'...","[{'credit_id': '52fe44439251416c9100a899', 'de...",https://image.tmdb.org/t/p/w500/fQC46NglNiEMZB...
46907,176271,2028550,111109.0,Century of Birthing,tl,An artist struggles to finish his work while a...,0.178241,0.0,"[{'id': 18, 'name': 'Drama'}]","[{'name': 'Sine Olivia', 'id': 19653}]",...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",9.0,3.0,"[{'id': 2679, 'name': 'artist'}, {'id': 14531,...","[{'cast_id': 1002, 'character': 'Sister Angela...","[{'credit_id': '52fe4af1c3a36847f81e9b15', 'de...",https://image.tmdb.org/t/p/w500/xZkmxsNmYXJbKV...
46910,176279,6980792,461257.0,Queerama,en,50 years after decriminalisation of homosexual...,0.163015,0.0,[],[],...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",0.0,0.0,[],[],"[{'credit_id': '593e676c92514105b702e68e', 'de...",https://image.tmdb.org/t/p/w500/s5UkZt6NTsrS7Z...

In [70]:
movies_data.shape

(6139, 21)

In [71]:
movies_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6139 entries, 1 to 46910
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   movieId               6139 non-null   int64
 1   imdbId                6139 non-null   int64
 2   tmdbId                6139 non-null   float64
 3   title                 6139 non-null   object
 4   original_language     6139 non-null   object
 5   overview              6139 non-null   object
 6   popularity            6139 non-null   float64
 7   budget                6139 non-null   float64
 8   genres                6139 non-null   object
 9   production_companies  6139 non-null   object
 10  production_countries  6139 non-null   object
 11  release_date          6139 non-null   object
 12  revenue               6139 non-null   float64
 13  runtime               6139 non-null   float64
 14  spoken_languages      6139 non-null   object
 15  vote_average          6139 non-null   float64
 16  vote_count            6139 non-null   float64
 17  keywords              6139 non-null   object
 18  cast                  6139 non-null   object
 19  crew                  6139 non-null   object
 20  poster_working_url    6139 non-null   object
dtypes: float64(7), int64(2), object(12)
memory usage: 1.0+ MB

In [72]:
movies_data.replace('[]', pd.NA, inplace=True)

# Drop rows with NaN values in any column
movies_data.dropna(inplace=True)

In [73]:
movies_data

,movieId,imdbId,tmdbId,title,original_language,overview,popularity,budget,genres,production_companies,...,release_date,revenue,runtime,spoken_languages,vote_average,vote_count,keywords,cast,crew,poster_working_url
1,2,113497,8844.0,Jumanji,en,When siblings Judy and Peter discover an encha...,17.015539,65000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...","[{'name': 'TriStar Pictures', 'id': 559}, {'na...",...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",6.9,2413.0,"[{'id': 10090, 'name': 'board game'}, {'id': 1...","[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",https://image.tmdb.org/t/p/w500/vzmL6fP7aPKNKP...
18,19,112281,9273.0,Ace Ventura: When Nature Calls,en,"Summoned from an ashram in Tibet, Ace finds hi...",8.205448,30000000.0,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...","[{'name': 'O Entertainment', 'id': 5682}, {'na...",...,1995-11-10,212385533.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",6.1,1128.0,"[{'id': 409, 'name': 'africa'}, {'id': 1551, '...","[{'cast_id': 1, 'character': 'Ace Ventura', 'c...","[{'credit_id': '52fe44dfc3a36847f80af28b', 'de...",https://image.tmdb.org/t/p/w500/wRlGnJhEzcxBjv...
19,20,113845,11517.0,Money Train,en,A vengeful New York transit cop decides to ste...,7.337906,60000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...","[{'name': 'Columbia Pictures', 'id': 5}]",...,1995-11-21,35431113.0,103.0,"[{'iso_639_1': 'en', 'name': 'English'}]",5.4,224.0,"[{'id': 380, 'name': 'brother brother relation...","[{'cast_id': 1, 'character': 'John', 'credit_i...","[{'credit_id': '52fe44509251416c750305a1', 'de...",https://image.tmdb.org/t/p/w500/jSozzzVOR2kfXg...
31,32,114746,63.0,Twelve Monkeys,en,"In the year 2035, convict James Cole reluctant...",12.297305,29500000.0,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...","[{'name': 'Universal Pictures', 'id': 33}, {'n...",...,1995-12-29,168840000.0,129.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",7.4,2470.0,"[{'id': 222, 'name': 'schizophrenia'}, {'id': ...","[{'cast_id': 41, 'character': 'James Cole', 'c...","[{'credit_id': '52fe4212c3a36847f8001ac7', 'de...",https://image.tmdb.org/t/p/w500/6Sj9wDu3YugthX...
33,34,112431,9598.0,Babe,en,Babe is a little pig who doesn't quite know hi...,14.404764,30000000.0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...","[{'name': 'Universal Pictures', 'id': 33}, {'n...",...,1995-07-18,254134910.0,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",6.0,756.0,"[{'id': 3020, 'name': 'sheep'}, {'id': 4931, '...","[{'cast_id': 1, 'character': 'Babe the Gallant...","[{'credit_id': '52fe450fc3a36847f80b9ff7', 'de...",https://image.tmdb.org/t/p/w500/gN6X3fwPya8pLf...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46878,176201,232750,5589.0,Šíleně smutná princezna,cs,No overview found.,0.375001,0.0,"[{'id': 10402, 'name': 'Music'}, {'id': 35, 'n...","[{'name': 'Filmové Studio Barrandov', 'id': 19...",...,1968-06-07,0.0,73.0,"[{'iso_639_1': 'cs', 'name': 'Český'}]",6.1,4.0,"[{'id': 3205, 'name': 'fairy tale'}, {'id': 13...","[{'cast_id': 12, 'character': 'princezna Helen...","[{'credit_id': '52fe440fc3a36847f807ffa3', 'de...",https://image.tmdb.org/t/p/w500/9h5eegOHh1zoaH...
46884,176215,36975,84710.0,Jungle Woman,en,Paula the ape woman (Acquanetta) is alive and ...,0.143223,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...","[{'name': 'Universal Pictures', 'id': 33}]",...,1944-06-01,0.0,61.0,"[{'iso_639_1': 'en', 'name': 'English'}]",5.8,2.0,"[{'id': 208422, 'name': 'paula dupree'}]","[{'cast_id': 2, 'character': 'Paula Dupree - t...","[{'credit_id': '52fe49099251416c910a0a89', 'de...",https://image.tmdb.org/t/p/w500/udZ3hvhC52su7U...
46894,176235,457437,14885.0,Pooh's Heffalump Halloween Movie,en,"It's Halloween in the 100 Acre Wood, and Roo's...",2.568495,0.0,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...","[{'name': 'Walt Disney Pictures', 'id': 2}]",...,2005-09-13,0.0,67.0,"[{'iso_639_1': 'en', 'name': 'English'}]",5.4,7.0,"[{'id': 3335, 'name': 'halloween'}, {'id': 193...","[{'cast_id': 1, 'character': 'Roo (voice)', 'c...","[{'credit_id': '52fe46249251416c7506e969', 'de...",https://image.tmdb.org/t/p/w500/yU6byKhpzHG1RF...
46898,176249,5690142,404604.0,Mom,hi,The bliss of a biology teacher’s family life i...,1.559596,0.0,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...","[{'name': 'Mad Films', 'id': 82459}, {'name': ...",...,2017-07-07,0.0,146.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",6.6,14.0,"[{'id': 155794, 'name': 'physical abuse'}, {'i...","[{'cast_id': 1, 'character': 'Devki Sabarwal',...","[{'credit_id': '58ee55bbc3a3683df500bd0f', 'de...",https://image.tmdb.org/t/p/w500/zZwbntqdfKdVgz...
46907,176271,2028550,111109.0,Century of Birthing,tl,An artist struggles to finish his work while a...,0.178241,0.0,"[{'id': 18, 'name': 'Drama'}]","[{'name': 'Sine Olivia', 'id': 19653}]",...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",9.0,3.0,"[{'id': 2679, 'name': 'artist'}, {'id': 14531,...","[{'cast_id': 1002, 'character': 'Sister Angela...","[{'credit_id': '52fe4af1c3a36847f81e9b15', 'de...",https://image.tmdb.org/t/p/w500/xZkmxsNmYXJbKV...

**Final movies data with 3660 rows and 21 columns**

1. Removed columns - ['adult', 'video', 'status'] in Movies_data(3660) and ['belongs_to_collection', 'homepage', 'tagline', 'imdb_id', 'poster_path', 'original_title'] in Movies_data(6139). 

2. In Movies_data(6139), all missing values are removed except the empty lists present for 'spoken_languages', 'production_countries', 'production_companies', 'genres', 'cast', 'crew' and 'keywords'.

3. In Movies_data(3660) all mising values are removed including empty lists.

4. Dim(Movies_data(3660)) = 3660x21

5. Dim(Movies_data(6139)) = 6139x24

In [74]:
movies_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3660 entries, 1 to 46907
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   movieId               3660 non-null   int64
 1   imdbId                3660 non-null   int64
 2   tmdbId                3660 non-null   float64
 3   title                 3660 non-null   object
 4   original_language     3660 non-null   object
 5   overview              3660 non-null   object
 6   popularity            3660 non-null   float64
 7   budget                3660 non-null   float64
 8   genres                3660 non-null   object
 9   production_companies  3660 non-null   object
 10  production_countries  3660 non-null   object
 11  release_date          3660 non-null   object
 12  revenue               3660 non-null   float64
 13  runtime               3660 non-null   float64
 14  spoken_languages      3660 non-null   object
 15  vote_average          3660 non-null   float64
 16  vote_count            3660 non-null   float64
 17  keywords              3660 non-null   object
 18  cast                  3660 non-null   object
 19  crew                  3660 non-null   object
 20  poster_working_url    3660 non-null   object
dtypes: float64(7), int64(2), object(12)
memory usage: 629.1+ KB